In [1]:
import pandas as pd

In [3]:
df_master = pd.read_csv('student.csv')

In [5]:
df_master.shape

(20, 10)

In [6]:
df_master.head()

,รหัสนักศึกษา,ชื่อ,อายุ,เพศ,คณะ,GPA,ส่วนสูง_cm,น้ำหนัก_kg,ชั่วโมงเรียน_ต่อสัปดาห์,วันที่ลงทะเบียน
0,64001,สมชาย,20.0,ชาย,วิทยาศาสตร์,3.21,170.0,65.0,15.0,2024-01-23
1,64002,สมหญิง,21.0,หญิง,วิทย์,3.45,165.0,58.0,20.0,2024-02-05
2,64003,NaN,NaN,Male,Science,3.67,175.0,NaN,25.0,2024-01-13
3,64004,สมศักดิ์,22.0,ช,คณะวิทยาศาสตร์,-1.00,168.0,70.0,10.0,2023-12-30
4,64005,สมใจ,19.0,ญ,วิศวะ,3.89,160.0,52.0,30.0,2024-01-27

In [7]:
print("="*50)
print("📋 ข้อมูลทั่วไปของ Dataset")
print("="*50)
df_master.info()

print("\n" + "="*50)
print("📊 สถิติเชิงพรรณนา")
print("="*50)
print(df_master.describe())

==================================================
📋 ข้อมูลทั่วไปของ Dataset
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   รหัสนักศึกษา             20 non-null     int64
 1   ชื่อ                     19 non-null     object
 2   อายุ                     17 non-null     float64
 3   เพศ                      18 non-null     object
 4   คณะ                      18 non-null     object
 5   GPA                      18 non-null     float64
 6   ส่วนสูง_cm               19 non-null     float64
 7   น้ำหนัก_kg               18 non-null     float64
 8   ชั่วโมงเรียน_ต่อสัปดาห์  18 non-null     float64
 9   วันที่ลงทะเบียน          20 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

==================================================
📊 สถิติเชิงพรรณนา
==================================================
       รหัสนักศึกษา        อายุ        GPA  ส่วนสูง_cm  น้ำหนัก_kg  \
count      20.00000   17.000000  18.000000   19.000000   18.000000
mean    64010.50000   28.470588   3.246111  167.684211   63.611111
std         5.91608   31.337114   1.123326    5.706260   10.279270
min     64001.00000   19.000000  -1.000000  158.000000   48.000000
25%     64005.75000   20.000000   3.215000  163.500000   55.250000
50%     64010.50000   21.000000   3.450000  168.000000   63.000000
75%     64015.25000   22.000000   3.670000  171.500000   71.500000
max     64020.00000  150.000000   4.500000  180.000000   82.000000

       ชั่วโมงเรียน_ต่อสัปดาห์
count                18.000000
mean                 21.388889
std                   6.598920
min                  10.000000
25%                  16.500000
50%                  21.500000
75%                  25.750000
max                  35.000000

In [8]:
missing_counts = df_master.isnull().sum()
print("\n❌ ค่าหายในแต่ละคอลัมน์:")
for col, count in missing_counts[missing_counts > 0].items():
    percentage = (count / len(df_master)) * 100
    print(f"   - {col}: {count} ค่า ({percentage:.1f}%)")

❌ ค่าหายในแต่ละคอลัมน์:
   - ชื่อ: 1 ค่า (5.0%)
   - อายุ: 3 ค่า (15.0%)
   - เพศ: 2 ค่า (10.0%)
   - คณะ: 2 ค่า (10.0%)
   - GPA: 2 ค่า (10.0%)
   - ส่วนสูง_cm: 1 ค่า (5.0%)
   - น้ำหนัก_kg: 2 ค่า (10.0%)
   - ชั่วโมงเรียน_ต่อสัปดาห์: 2 ค่า (10.0%)

In [9]:
data = {
    'ชื่อ': ['ก้อง', 'กล้า', 'กิ่ง', 'กานต์', 'กุล', 'กบ', 'กิตติ', 'กมล', 'กร', 'กนก'],
    'อายุ': [21, 22, 20, 21, None, 22, 21, 20, 21, 22],  # เฉพาะกุลไม่กรอกอายุ
    'GPA': [3.5, 3.2, 3.8, 3.0, 3.7, 3.3, 3.6, 3.4, 3.1, 3.9]
}

In [10]:
df = pd.DataFrame(data)

In [11]:
df.shape

(10, 3)

In [12]:
df.head()

    ชื่อ  อายุ  GPA
0   ก้อง  21.0  3.5
1   กล้า  22.0  3.2
2   กิ่ง  20.0  3.8
3  กานต์  21.0  3.0
4    กุล   NaN  3.7

In [13]:
df_clean = df.dropna()

In [14]:
df_clean

    ชื่อ  อายุ  GPA
0   ก้อง  21.0  3.5
1   กล้า  22.0  3.2
2   กิ่ง  20.0  3.8
3  กานต์  21.0  3.0
5     กบ  22.0  3.3
6  กิตติ  21.0  3.6
7    กมล  20.0  3.4
8     กร  21.0  3.1
9    กนก  22.0  3.9

In [15]:
data = {
    'ชื่อ': ['สมชาย', 'สมหญิง', 'สมศักดิ์', 'สมใจ', 'สมปอง'],
    'อายุ': [20, None, 19, 22, 21]  # สมหญิงไม่ได้กรอกอายุ
}
df = pd.DataFrame(data)

In [16]:
df.head()

       ชื่อ  อายุ
0     สมชาย  20.0
1    สมหญิง   NaN
2  สมศักดิ์  19.0
3      สมใจ  22.0
4     สมปอง  21.0

In [17]:
mean_age = df['อายุ'].mean()

In [18]:
mean_age

np.float64(20.5)

In [19]:
df['อายุ'].fillna(mean_age, inplace=True)

/tmp/ipython-input-2649356385.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['อายุ'].fillna(mean_age, inplace=True)

In [20]:
df

       ชื่อ  อายุ
0     สมชาย  20.0
1    สมหญิง  20.5
2  สมศักดิ์  19.0
3      สมใจ  22.0
4     สมปอง  21.0

In [21]:
data = {
    'ชื่อ': ['สมชาย', 'สมหญิง', 'สมศักดิ์', 'สมใจ', 'สมปอง'],
    'คณะ': ['วิทยาศาสตร์', 'วิทยาศาสตร์', None, 'ศิลปศาสตร์', 'วิทย์']
}

In [22]:
data = {
    'ชื่อ': ['สมชาย', 'สมหญิง', 'สมศักดิ์', 'สมใจ', 'สมปอง'],
    'คณะ': ['วิทยาศาสตร์', 'วิทยาศาสตร์', None, 'ศิลปศาสตร์', 'วิทย์']
}

In [23]:
df = pd.DataFrame(data)

In [24]:
df.head()

       ชื่อ          คณะ
0     สมชาย  วิทยาศาสตร์
1    สมหญิง  วิทยาศาสตร์
2  สมศักดิ์         None
3      สมใจ   ศิลปศาสตร์
4     สมปอง        วิทย์

In [25]:
df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

/tmp/ipython-input-109974322.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['คณะ'].fillna(df['คณะ'].mode()[0], inplace=True)

In [26]:
df

       ชื่อ          คณะ
0     สมชาย  วิทยาศาสตร์
1    สมหญิง  วิทยาศาสตร์
2  สมศักดิ์  วิทยาศาสตร์
3      สมใจ   ศิลปศาสตร์
4     สมปอง        วิทย์

In [27]:
def standardize_faculty(name):
    if name in ['วิทยาศาสตร์', 'วิทย์', 'Science', 'คณะวิทยาศาสตร์']:
        return 'วิทยาศาสตร์'
    elif name in ['ศิลปศาสตร์', 'ศิลป์', 'Arts']:
        return 'ศิลปศาสตร์'
    else:
        return name

In [28]:
df['คณะ_มาตรฐาน'] = df['คณะ'].apply(standardize_faculty)

In [29]:
df['คณะ_มาตรฐาน']

0    วิทยาศาสตร์
1    วิทยาศาสตร์
2    วิทยาศาสตร์
3     ศิลปศาสตร์
4    วิทยาศาสตร์
Name: คณะ_มาตรฐาน, dtype: object

In [30]:
data = {
    'ชื่อ': ['นักศึกษา1', 'นักศึกษา2', 'นักศึกษา3', 'นักศึกษา4', 'นักศึกษา5',
             'นักศึกษา6', 'นักศึกษา7', 'นักศึกษา8', 'นักศึกษา9', 'นักศึกษา10'],
    'อายุ': [20, 21, 22, 19, 20, 150, 21, 22, 23, 18]  # 150 คือค่าผิดปกติ
}

In [31]:
df = pd.DataFrame(data)

In [32]:
print(f"\nค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - {df['อายุ'].mean():.2f}")

ค่าเฉลี่ยอายุ (รวมค่าผิดปกติ) - 33.60

In [33]:
Q1 = df['อายุ'].quantile(0.25)
Q3 = df['อายุ'].quantile(0.75)

In [34]:
IQR = Q3-Q1

In [35]:
IQR

np.float64(2.0)

In [36]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [37]:
print(lower_bound)
print(upper_bound)

17.0
25.0

In [38]:
df_no_outliers = df[(df['อายุ'] >= lower_bound) & (df['อายุ'] <= upper_bound)]

In [39]:
df_no_outliers

         ชื่อ  อายุ
0   นักศึกษา1    20
1   นักศึกษา2    21
2   นักศึกษา3    22
3   นักศึกษา4    19
4   นักศึกษา5    20
6   นักศึกษา7    21
7   นักศึกษา8    22
8   นักศึกษา9    23
9  นักศึกษา10    18

In [40]:
df['อายุ'] >= lower_bound

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: อายุ, dtype: bool

In [41]:
df['อายุ'] >= upper_bound

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9    False
Name: อายุ, dtype: bool

In [42]:
data = pd.DataFrame({
    'ชื่อ': ['A', 'B', 'C', 'D'],
    'คณะ': ['วิทย์', 'ศิลป์', 'วิทย์', 'วิศวะ']
})

In [43]:
data_encoded = pd.get_dummies(data, columns=['คณะ'])
print(data_encoded)

  ชื่อ  คณะ_วิทย์  คณะ_วิศวะ  คณะ_ศิลป์
0    A       True      False      False
1    B      False      False       True
2    C       True      False      False
3    D      False       True      False

In [44]:
coffee_data = pd.DataFrame({
    'วันเวลา': pd.to_datetime(['2024-01-15 07:30', '2024-01-15 12:00',
                               '2024-01-15 16:30', '2024-01-16 08:00']),
    'ยอดขาย': [1500, 3200, 2100, 1800]
})

In [45]:
coffee_data

              วันเวลา  ยอดขาย
0 2024-01-15 07:30:00    1500
1 2024-01-15 12:00:00    3200
2 2024-01-15 16:30:00    2100
3 2024-01-16 08:00:00    1800

In [46]:
coffee_data['ชั่วโมง'] = coffee_data['วันเวลา'].dt.hour

In [47]:
coffee_data

              วันเวลา  ยอดขาย  ชั่วโมง
0 2024-01-15 07:30:00    1500        7
1 2024-01-15 12:00:00    3200       12
2 2024-01-15 16:30:00    2100       16
3 2024-01-16 08:00:00    1800        8

In [48]:
coffee_data['วันในสัปดาห์'] = coffee_data['วันเวลา'].dt.day_name()

In [49]:
coffee_data

              วันเวลา  ยอดขาย  ชั่วโมง วันในสัปดาห์
0 2024-01-15 07:30:00    1500        7       Monday
1 2024-01-15 12:00:00    3200       12       Monday
2 2024-01-15 16:30:00    2100       16       Monday
3 2024-01-16 08:00:00    1800        8      Tuesday

In [50]:
coffee_data['ช่วงเวลา'] = pd.cut(coffee_data['ชั่วโมง'],
                                  bins=[0, 10, 14, 18, 24],
                                  labels=['เช้า', 'กลางวัน', 'บ่าย', 'เย็น'])

In [51]:
coffee_data

              วันเวลา  ยอดขาย  ชั่วโมง วันในสัปดาห์ ช่วงเวลา
0 2024-01-15 07:30:00    1500        7       Monday     เช้า
1 2024-01-15 12:00:00    3200       12       Monday  กลางวัน
2 2024-01-15 16:30:00    2100       16       Monday     บ่าย
3 2024-01-16 08:00:00    1800        8      Tuesday     เช้า

In [52]:
print(coffee_data[['วันเวลา', 'ช่วงเวลา', 'ยอดขาย']])

              วันเวลา ช่วงเวลา  ยอดขาย
0 2024-01-15 07:30:00     เช้า    1500
1 2024-01-15 12:00:00  กลางวัน    3200
2 2024-01-15 16:30:00     บ่าย    2100
3 2024-01-16 08:00:00     เช้า    1800

In [53]:
student_health = pd.DataFrame({
    'ชื่อ': ['สมชาย', 'สมหญิง', 'สมศักดิ์'],
    'ส่วนสูง_cm': [170, 165, 175],
    'น้ำหนัก_kg': [65, 55, 80]
})

In [54]:
student_health['BMI'] = student_health['น้ำหนัก_kg'] / (student_health['ส่วนสูง_cm']/100)**2
student_health['สุขภาพ'] = pd.cut(student_health['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=['ผอม', 'ปกติ', 'อ้วน', 'อ้วนมาก'])

In [55]:
student_health

       ชื่อ  ส่วนสูง_cm  น้ำหนัก_kg        BMI สุขภาพ
0     สมชาย         170          65  22.491349   ปกติ
1    สมหญิง         165          55  20.202020   ปกติ
2  สมศักดิ์         175          80  26.122449   อ้วน

In [56]:
print(student_health[['ชื่อ', 'BMI', 'สุขภาพ']])

       ชื่อ        BMI สุขภาพ
0     สมชาย  22.491349   ปกติ
1    สมหญิง  20.202020   ปกติ
2  สมศักดิ์  26.122449   อ้วน

In [57]:
raw_data = {
    'รหัสนักศึกษา': ['64001', '64002', '64003', '64004', '64005'],
    'ชื่อ': ['สมชาย', 'สมหญิง', None, 'สมศักดิ์', 'สมใจ'],
    'คณะ': ['วิทย์', 'ศิลปศาสตร์', 'วิทยาศาสตร์', 'Arts', 'วิศวะ'],
    'ชั้นปี': [2, 3, 2, None, 4],
    'GPA': [3.2, 3.8, -1, 2.9, 4.5],  # -1 และ 4.5 ผิดปกติ
    'กิจกรรม': ['กีฬา', 'ดนตรี', 'กีฬา,ดนตรี', None, 'อาสา'],
    'เวลาเข้าร่วม': ['08:00', '9.30', '08:30', '08:00', None]
}

df_student = pd.DataFrame(raw_data)

In [58]:
faculty_mapping = {
    'วิทย์': 'วิทยาศาสตร์',
    'วิทยาศาสตร์': 'วิทยาศาสตร์',
    'ศิลปศาสตร์': 'ศิลปศาสตร์',
    'Arts': 'ศิลปศาสตร์',
    'วิศวะ': 'วิศวกรรมศาสตร์'
}

In [59]:
faculty_mapping

{'วิทย์': 'วิทยาศาสตร์',
 'วิทยาศาสตร์': 'วิทยาศาสตร์',
 'ศิลปศาสตร์': 'ศิลปศาสตร์',
 'Arts': 'ศิลปศาสตร์',
 'วิศวะ': 'วิศวกรรมศาสตร์'}

In [60]:
df_student['คณะ'] = df_student['คณะ'].map(faculty_mapping)

In [61]:
df_student

  รหัสนักศึกษา      ชื่อ             คณะ  ชั้นปี  GPA     กิจกรรม เวลาเข้าร่วม
0        64001     สมชาย     วิทยาศาสตร์     2.0  3.2        กีฬา        08:00
1        64002    สมหญิง      ศิลปศาสตร์     3.0  3.8       ดนตรี         9.30
2        64003      None     วิทยาศาสตร์     2.0 -1.0  กีฬา,ดนตรี        08:30
3        64004  สมศักดิ์      ศิลปศาสตร์     NaN  2.9        None        08:00
4        64005      สมใจ  วิศวกรรมศาสตร์     4.0  4.5        อาสา         None